@startuml Loop

start

:currentSeconds = 0
currentMillis = 0
oldMillis = 0;

note right 
    setup()
end note

partition loop() {
repeat
    :nowMillis = millis();
    :currentMillis = nowMillis - oldMillis;
    :oldMillis = nowMillis; 
    if (currentMillis > 1000) then
        :currentSeconds++;
    endif
repeat while ()
}
stop

@enduml
